# Generated by Django 4.1.4 on 2023-07-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_image'),
        ('categories', '0002_category_image 2'),
    ]

    operations = [
    ]
