# Generated by Django 4.1.4 on 2023-07-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at'),
        ('orders', '0002_order_created_at 2'),
    ]

    operations = [
    ]
